### ISSUE TITLE
Interactive pseudo-selectors should be ordered by state and not color.

### ISSUE THREAD

**Issue by mikebarnhardt** [mikebarnhardt/ancient#10]
Having pseudo-selectors interspersed between color definitions prohibits correct cascading between color changes.

```css
.color-gray-100 { color: hsl(0, 0, 96%) }
.hover\:color-gray-100:hover { color: hsl(0, 0, 96%) }
.focus\:color-gray-100:focus { color: hsl(0, 0, 96%) }

.color-blue-600 { color: hsl(0, 0, 96%) }
.hover\:color-blue-600:hover { color: hsl(0, 0, 96%) }
.focus\:color-blue-600:focus { color: hsl(0, 0, 96%) }
```

```jsx
<div className="focus:background-blue-600 color-gray-100 focus:color-gray-100 hover:color-blue-600" />
```

Hover overrides focus on the color property in the example which is not correct. Re-ordering all color properties by pseudo-selector should fix the issue.

```css
.color-gray-100 { }
.color-blue-600 { }
.hover\:color-gray-100 { }
.hover\:color-blue-600 { }
.focus\:color-gray-100 { }
.focus\:color-blue-600 { }
```
